name: "Jmeter"
description: "Runs jmeter zap proxy before reporting the results."
author: "hoainamnv34"
inputs: 
  target:
    description: "The URL of the application to be tested"
    required: true
  zap-host:
    description: "zap host"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --target 
  - "${{ inputs.target }}" 
  - --zap-host 
  - "${{ inputs.zap-host }}"
